### ISSUE TITLE
Wrong rate? Foute tarief code?

### ISSUE THREAD

**Issue by RZO00** [gruijter/com.gruijter.beeclear#3]
Beste Robin,
Ik ben begonnen met het gebruik van jou app in mijn nieuwe Homey, heel handig echter,
de app geeft bij mij altijd laag tarief aan terwijl deze in werkelijkheid van hoog naar laag switched. BeeClear zelf geeft het goed aan.
Of is mijn interpretatie fout en is Nee-Laagtarief Hoogtarief. In dat geval is er geen issue.

Zou je er eens naar willen kijken? Versie 2.2.2

Vast reuze bedankt,
Rob Oosterbaan rob.oosterbaan@gmail.com

![Beeclear app](https://user-images.githubusercontent.com/108123700/175505498-986262c0-c5dc-446d-8643-582dfd6f9d95.jpg)

**Comment by gruijter** [comment]
Laag tarief: nee betekent inderdaad dat het hoog tarief is.
